version: '3.8'
name: rtvagdstore
services:
    database:
        image: postgres:16.1-alpine
        restart: always
        env_file: './.env'
        volumes:
            - rtvAgdStore-db:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - rtvAgdStore-network
    fileStorage:
        image: minio/minio
        restart: always
        ports:
            - '9000:9000'
            - '9001:9001'
        networks:
            - rtvAgdStore-network
        volumes:
            -   minio-storage:/data
        env_file: './.env'
        command: server --console-address ":9001" /data
volumes:
    rtvAgdStore-db:
    minio-storage:
networks:
    rtvAgdStore-network:
        driver: bridge